export type QuestionCategory =
  | "structure_systems"
  | "interior"
  | "exterior_community"
  | "showing_disclosures"
  | "listing_details";

export type QuestionType = "text" | "multi_select" | "single_select";

export interface SmartQuestion {
  id: string;
  category: QuestionCategory;
  label: string;
  helper?: string;
  type?: QuestionType;
  options?: string[];
}

export const SMART_QUESTIONS: SmartQuestion[] = [
  // ── Listing details (new) ──
  {
    id: "ownership_type",
    category: "listing_details",
    label: "Ownership type",
    type: "single_select",
    options: ["Fee Simple", "Leasehold", "Condominium", "Cooperative", "Other"],
  },
  {
    id: "listing_agreement_type",
    category: "listing_details",
    label: "Listing agreement type",
    type: "single_select",
    options: [
      "Exclusive Right to Sell",
      "Exclusive Agency",
      "Open Listing",
      "Net Listing",
    ],
  },
  {
    id: "property_subtype",
    category: "listing_details",
    label: "Property subtype",
    type: "single_select",
    options: [
      "Single Family Residence",
      "Townhouse",
      "Villa",
      "Manufactured Home",
      "Mobile Home",
      "Modular Home",
      "Other",
    ],
  },
  {
    id: "list_price",
    category: "listing_details",
    label: "List price ($)",
    helper: "The asking price you plan to enter in Stellar MLS.",
  },
  {
    id: "directions",
    category: "listing_details",
    label: "Driving directions",
    helper: "Example: From US-41, head east on SR-54, right on Collier Pkwy, left on Wild Plum Ct.",
  },

  // ── Structure & systems ──
  {
    id: "roof_type_age",
    category: "structure_systems",
    label: "Roof type & approximate age",
    helper:
      "Example: Architectural shingle roof, replaced in 2018 (approx. 7 years old).",
  },
  {
    id: "hvac_type_age",
    category: "structure_systems",
    label: "HVAC type & approximate age",
    helper:
      "Example: 3-ton heat pump system, replaced in 2021 with new ductwork.",
  },
  {
    id: "water_heater",
    category: "structure_systems",
    label: "Water heater type & age",
    helper: "Example: 50-gal electric tank, 2020. Or: Tankless gas, 2022.",
  },
  {
    id: "water_sewer",
    category: "structure_systems",
    label: "Water & sewer",
    type: "multi_select",
    options: [
      "Public Water",
      "Well Water",
      "Public Sewer",
      "Septic Tank",
      "Reclaimed Water for Irrigation",
    ],
    helper: "Select all that apply. Add details in the text field if needed.",
  },
  {
    id: "electric_provider",
    category: "structure_systems",
    label: "Electric / gas provider",
    helper: "Example: Duke Energy, TECO. Or: No gas service.",
  },
  {
    id: "construction_materials",
    category: "structure_systems",
    label: "Construction / exterior wall material",
    type: "multi_select",
    options: [
      "Block/Concrete",
      "Stucco",
      "Brick",
      "Frame/Wood",
      "Vinyl Siding",
      "HardiePlank/Cement Fiber",
      "Stone",
    ],
  },
  {
    id: "foundation_type",
    category: "structure_systems",
    label: "Foundation type",
    type: "single_select",
    options: ["Slab", "Crawl Space", "Basement", "Pilings/Stilts", "Other"],
  },

  // ── Interior ──
  {
    id: "flooring",
    category: "interior",
    label: "Flooring types",
    type: "multi_select",
    options: [
      "Tile",
      "Hardwood",
      "Laminate",
      "Luxury Vinyl Plank (LVP)",
      "Carpet",
      "Marble",
      "Terrazzo",
      "Concrete",
    ],
    helper: "Select all that apply.",
  },
  {
    id: "appliances",
    category: "interior",
    label: "Appliances included",
    type: "multi_select",
    options: [
      "Dishwasher",
      "Disposal",
      "Dryer",
      "Microwave",
      "Range/Oven",
      "Refrigerator",
      "Washer",
      "Range Hood",
      "Ice Maker",
      "Wine Cooler",
      "Cooktop",
      "Double Oven",
      "Convection Oven",
      "Trash Compactor",
    ],
    helper: "Select all that apply. Add brand/age details in the text field if desired.",
  },
  {
    id: "interior_features",
    category: "interior",
    label: "Interior features",
    type: "multi_select",
    options: [
      "Walk-in Closet(s)",
      "Crown Molding",
      "Tray Ceiling(s)",
      "Vaulted Ceiling(s)",
      "Open Floorplan",
      "Split Bedrooms",
      "Built-in Shelving",
      "Eat-in Kitchen",
      "Kitchen Island",
      "Granite Countertops",
      "Quartz Countertops",
      "Solid Surface Countertops",
      "Pantry",
      "Breakfast Bar",
      "Primary Bedroom Main Floor",
      "Attic",
      "Smart Home System",
      "Ceiling Fan(s)",
      "Recessed Lighting",
      "Window Treatments",
    ],
    helper: "Select all that apply.",
  },
  {
    id: "laundry_features",
    category: "interior",
    label: "Laundry features",
    type: "multi_select",
    options: [
      "Inside",
      "Laundry Room",
      "Washer Hookup",
      "Dryer Hookup - Electric",
      "Dryer Hookup - Gas",
      "Laundry Closet",
      "Upper Level",
      "Main Level",
    ],
  },
  {
    id: "window_features",
    category: "interior",
    label: "Window features",
    type: "multi_select",
    options: [
      "Impact Glass / Hurricane",
      "Double Pane",
      "Low-E Windows",
      "Blinds",
      "Shutters",
      "Window Treatments",
      "Skylights",
      "Tinted Windows",
    ],
  },
  {
    id: "fireplace",
    category: "interior",
    label: "Fireplace",
    type: "single_select",
    options: [
      "None",
      "Wood Burning",
      "Gas",
      "Electric",
      "Decorative / Non-functional",
    ],
  },
  {
    id: "key_upgrades",
    category: "interior",
    label: "Key interior upgrades or recent renovations",
    helper:
      "Example: Remodeled kitchen (2022), updated primary bath, new interior paint.",
  },

  // ── Exterior & community ──
  {
    id: "exterior_features",
    category: "exterior_community",
    label: "Exterior features",
    type: "multi_select",
    options: [
      "Covered Patio",
      "Screened Porch/Lanai",
      "Open Patio",
      "Deck",
      "Outdoor Kitchen",
      "Built-in Grill",
      "Fenced Yard",
      "Privacy Fence",
      "Irrigation System",
      "Landscape Lighting",
      "Gutters",
      "Sidewalk",
      "French Doors",
      "Sliding Doors",
      "Hurricane Shutters",
      "Storage Shed",
      "Dog Run",
    ],
    helper: "Select all that apply.",
  },
  {
    id: "pool_waterfront_garage",
    category: "exterior_community",
    label: "Pool / spa / waterfront details",
    type: "multi_select",
    options: [
      "In-ground Pool",
      "Above-ground Pool",
      "Screened Pool",
      "Heated Pool",
      "Saltwater Pool",
      "Spa/Hot Tub",
      "No Pool",
      "Community Pool Only",
      "Pond/Lake View",
      "Canal Front",
      "Waterfront",
      "No Waterfront",
    ],
    helper: "Select all that apply. Add additional details in the text field.",
  },
  {
    id: "parking_garage",
    category: "exterior_community",
    label: "Parking / garage / carport",
    type: "multi_select",
    options: [
      "Attached Garage",
      "Detached Garage",
      "1-car Garage",
      "2-car Garage",
      "3-car Garage",
      "Carport",
      "Driveway",
      "Circular Driveway",
      "Off-street Parking",
      "Golf Cart Garage",
      "RV Parking",
      "No Garage",
    ],
  },
  {
    id: "lot_features",
    category: "exterior_community",
    label: "Lot features",
    type: "multi_select",
    options: [
      "Corner Lot",
      "Cul-de-sac",
      "Oversized Lot",
      "Conservation View",
      "Cleared",
      "Landscaped",
      "Mature Landscaping",
      "Near Golf Course",
      "Near Public Transit",
      "Paved Road",
      "Sidewalk",
      "Street Lights",
      "Zero Lot Line",
    ],
  },
  {
    id: "hoa_fees_amenities",
    category: "exterior_community",
    label: "HOA / CDD fees & amenities",
    helper:
      "Monthly/annual fees, community pool, clubhouse, gated entry, playground, etc.",
  },
  {
    id: "hoa_restrictions",
    category: "exterior_community",
    label: "HOA restrictions / approval required",
    type: "single_select",
    options: [
      "No HOA",
      "HOA - No Approval Required",
      "HOA - Approval Required",
      "HOA - Deed Restrictions Only",
      "CDD Only",
      "HOA + CDD",
    ],
  },
  {
    id: "community_amenities",
    category: "exterior_community",
    label: "Community amenities (if HOA/CDD)",
    type: "multi_select",
    options: [
      "Community Pool",
      "Clubhouse",
      "Fitness Center",
      "Tennis Courts",
      "Pickleball Courts",
      "Basketball Courts",
      "Playground",
      "Dog Park",
      "Walking/Jogging Trails",
      "Gated Entry",
      "Guard Gate",
      "Golf Course",
      "Boat Ramp/Dock",
      "Lake Access",
      "Park",
    ],
  },

  // ── Showing & disclosures ──
  {
    id: "showing_instructions",
    category: "showing_disclosures",
    label: "Showing instructions",
    helper:
      "Example: 2-hour notice via ShowingTime, lockbox on front door, ring doorbell before entering.",
  },
  {
    id: "lockbox_type",
    category: "showing_disclosures",
    label: "Lockbox type & location",
    type: "single_select",
    options: [
      "Supra - Front Door",
      "Supra - Side Door",
      "Supra - Garage",
      "Combo Lock - Front Door",
      "Combo Lock - Garage",
      "No Lockbox / Call Agent",
      "Electronic Smart Lock",
    ],
  },
  {
    id: "occupancy_status",
    category: "showing_disclosures",
    label: "Occupancy status",
    type: "single_select",
    options: ["Owner Occupied", "Tenant Occupied", "Vacant", "Seasonally Occupied"],
  },
  {
    id: "material_disclosures",
    category: "showing_disclosures",
    label: "Material facts or disclosures (for private remarks)",
    helper:
      "Example: Roof near end of life, previous settlement repair, audio/video on premises.",
  },
  {
    id: "flood_zone",
    category: "showing_disclosures",
    label: "Flood zone designation",
    type: "single_select",
    options: [
      "Zone X (minimal risk)",
      "Zone AE (high risk)",
      "Zone AH",
      "Zone VE (coastal high hazard)",
      "Zone A (high risk, no BFE)",
      "Unknown - check FEMA map",
    ],
    helper: "Use the FEMA flood map link in MLS Fields to verify.",
  },
  {
    id: "accessibility_features",
    category: "showing_disclosures",
    label: "Accessibility / ADA features",
    type: "multi_select",
    options: [
      "None",
      "Wheelchair Accessible",
      "Accessible Entrance",
      "Wide Doorways",
      "Low Threshold Shower",
      "Grab Bars",
      "Single-story Living",
      "Elevator",
    ],
  },
];
